name: Ant and choco build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Get a Java build environment
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Run the ant build
      - name: Build with Ant
        run: ant -p

      # Run choco commands
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h

      # Only while releasing a tag
      - name: Run choco release command when getting a TAG
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Hello tag ${{ github.ref }}"