name: Ant and choco build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Ant
        run: ant -v
      - uses: crazy-max/ghaction-chocolatey@v1
      - name: Choco help
        with:
          args: -h
